# NOTE: docker-compose will create network automatically
# this allows the containers to communicate with each other
version: '3.4'

services:
  pastebin-s3:
    build: pastebin-s3
    image: nathanesau/pastebin-clone:pastebin-s3
    container_name: pastebin-s3
    restart: always
    #volumes:
    #  - data01:/usr/share/elasticsearch/data
    #ports:
    #  - 9200:9200
    network_mode: host
  pastebin-app:
    build: pastebin-app
    image: nathanesau/pastebin-clone:pastebin-app
    container_name: pastebin-app
    restart: always
    volumes:
      - data02:/data
    ports:
      - 6000:6000
    network_mode: host
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/app.db
      - ELASTICSEARCH_URL=http://127.0.0.1:9200/
    depends_on:
      - twitter-search
  twitter-nginx:
    build: twitter-nginx
    image: nathanesau/twitter-clone:twitter-nginx
    container_name: twitter-nginx
    restart: always
    ports:
      - 80:80
    network_mode: host
    depends_on:
      - twitter-app

volumes:
  data01:
    driver: local
  data02:
    driver: local