# NOTE: docker-compose will create network automatically
# this allows the containers to communicate with each other
version: '3.4'

services:
  pastebin-app:
    build: pastebin-app
    image: nathanesau/pastebin-clone:pastebin-app
    container_name: pastebin-app
    restart: always
    volumes:
      - data01:/data
      - data02:/pastes
    ports:
      - 5001:5001
    network_mode: host
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////data/app.db
      - PASTES_FOLDER=/pastes
  pastebin-bgtasks:
    build: pastebin-bgtasks
    image: nathanesau/pastebin-clone:pastebin-bgtasks
    container_name: pastebin-bgtasks
    restart: always
    network_mode: host
    environment:
      - PASTEBIN_API_URL=http://127.0.0.1:5001/pastebin-clone/api
    depends_on:
      - pastebin-app
  pastebin-nginx:
    build: pastebin-nginx
    image: nathanesau/pastebin-clone:pastebin-nginx
    container_name: pastebin-nginx
    restart: always
    ports:
      - 80:80
    network_mode: host
    depends_on:
      - pastebin-app

volumes:
  data01:
    driver: local
  data02:
    driver: local